fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
    firewall:
      repo: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
    sshkeys:
      repo: 'git://github.com/puppetlabs/puppetlabs-sshkeys_core.git'
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git://github.com/puppetlabs/provision.git'
  symlinks:
    ssh: "#{source_dir}"
