---

spec/spec_helper.rb:
  hiera_config: spec/fixtures/hiera/hiera.yaml
  coverage_report: true

spec/default_facts.yml:
  extra_facts:
    ssh_version: OpenSSH_6.6.1p1
    root_home: /root

.travis.yml:
  delete: true
".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/ci.yml:
  unmanaged: true
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
